version: '3.8'

services:
  web:
    build: ./
    command: "gunicorn --bind 0.0.0.0:5000 app.main:app"
    volumes:
      - ./:/akindi-discord-mcq
    ports:
      - 5000:5000
    env_file:
      - ./.env

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4551:4551
    links:
      - web
    env_file:
      - ./.env
