import os


CLIENT_PUBLIC_KEY = os.getenv("CLIENT_PUBLIC_KEY")
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")

DISCORD_API_VERSION = os.getenv("DISCORD_API_VERSION", "v10")
DISCORD_API_BASE_URL = f"https://discord.com/api"

GUILD_ID = os.getenv("GUILD_ID", "1079715462058889308")
CHANNEL_ID = os.getenv("CHANNEL_ID", "1079715534322548816")

DISCORD_TOKEN_ENDPOINT = f"{DISCORD_API_BASE_URL}/{DISCORD_API_VERSION}/oauth2/token"

REDIRECT_URI = os.getenv("REDIRECT_URI")
